export interface TemplateCatalogItem {
  id: string;
  name: string;
  description: string;
  category: string;
  categoryLabel: string;
  isPremium: boolean;
  isPopular?: boolean;
  colors: string;
}

export const TEMPLATE_CATALOG: TemplateCatalogItem[] = [
  {
    id: 'modern-professional',
    name: 'Modern Professional',
    description: 'Clean and contemporary design perfect for corporate roles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    isPopular: true,
    colors: 'from-blue-500 to-blue-700',
  },
  {
    id: 'tech-minimal',
    name: 'Tech Minimal',
    description: 'Sleek layout optimized for tech and startup positions.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: false,
    colors: 'from-slate-600 to-slate-800',
  },
  {
    id: 'executive-classic',
    name: 'Executive Classic',
    description: 'Elegant template for senior leadership positions.',
    category: 'executive',
    categoryLabel: 'Executive',
    isPremium: true,
    colors: 'from-gray-700 to-gray-900',
  },
  {
    id: 'creative-bold',
    name: 'Creative Bold',
    description: 'Eye-catching style for marketing and creative roles.',
    category: 'creative',
    categoryLabel: 'Creative',
    isPremium: true,
    colors: 'from-fuchsia-500 to-rose-700',
  },
  {
    id: 'simple-clean',
    name: 'Simple Clean',
    description: 'Minimal design that keeps focus on experience.',
    category: 'modern',
    categoryLabel: 'Modern',
    isPremium: false,
    colors: 'from-teal-500 to-teal-700',
  },
  {
    id: 'startup-modern',
    name: 'Startup Modern',
    description: 'Dynamic and modern structure for fast-paced companies.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: true,
    colors: 'from-orange-500 to-orange-700',
  },
  {
    id: 'consultant-pro',
    name: 'Consultant Pro',
    description: 'Structured format for consulting and advisory profiles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: true,
    colors: 'from-indigo-500 to-indigo-700',
  },
  {
    id: 'academic-formal',
    name: 'Academic Formal',
    description: 'Traditional format for research and academic careers.',
    category: 'academic',
    categoryLabel: 'Academic',
    isPremium: false,
    colors: 'from-green-600 to-green-800',
  },
  {
    id: 'accountant-template',
    name: 'Accountant Precision',
    description: 'Structured finance-focused format for accounting and audit roles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    colors: 'from-slate-700 to-slate-900',
  },
  {
    id: 'consultant-template',
    name: 'Consultant Strategy',
    description: 'Clean strategy-forward layout for consulting profiles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: true,
    colors: 'from-blue-700 to-indigo-900',
  },
  {
    id: 'data-science-template',
    name: 'Data Science Insight',
    description: 'Metrics-first layout for data science and analytics roles.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: true,
    colors: 'from-cyan-600 to-blue-900',
  },
  {
    id: 'devops-template',
    name: 'DevOps Infra',
    description: 'Infrastructure-oriented format for SRE and DevOps profiles.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: true,
    colors: 'from-emerald-600 to-teal-900',
  },
  {
    id: 'finance-template',
    name: 'Finance Analyst',
    description: 'Polished structure for finance and FP&A roles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    colors: 'from-slate-700 to-blue-900',
  },
  {
    id: 'frontend-template',
    name: 'Front-End Craft',
    description: 'Visual hierarchy focused template for front-end engineers.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: false,
    colors: 'from-sky-500 to-indigo-700',
  },
  {
    id: 'legal-template',
    name: 'Legal Counsel',
    description: 'Formal legal style for counsel and legal advisor roles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: true,
    colors: 'from-zinc-700 to-slate-900',
  },
  {
    id: 'marketing-template',
    name: 'Marketing Growth',
    description: 'Campaign and impact-driven template for growth roles.',
    category: 'creative',
    categoryLabel: 'Creative',
    isPremium: false,
    colors: 'from-rose-500 to-orange-700',
  },
  {
    id: 'medical-template',
    name: 'Medical Specialist',
    description: 'Clear healthcare-focused layout for medical professionals.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: true,
    colors: 'from-teal-600 to-cyan-800',
  },
  {
    id: 'nurse-template',
    name: 'Nurse Care',
    description: 'Readable, credential-forward template for nursing roles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    colors: 'from-green-600 to-emerald-800',
  },
  {
    id: 'paralegal-template',
    name: 'Paralegal Brief',
    description: 'Structured legal support format for paralegal experience.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    colors: 'from-stone-600 to-zinc-800',
  },
  {
    id: 'product-manager-template',
    name: 'Product Manager',
    description: 'Outcome-driven layout for PM and product leadership.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: true,
    colors: 'from-indigo-600 to-purple-800',
  },
  {
    id: 'sales-template',
    name: 'Sales Performance',
    description: 'Quota and pipeline focused template for sales roles.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    colors: 'from-amber-600 to-red-700',
  },
  {
    id: 'startup-template',
    name: 'Startup Operator',
    description: 'Fast-paced startup style with execution highlights.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: false,
    colors: 'from-violet-600 to-fuchsia-800',
  },
  {
    id: 'ux-designer-template',
    name: 'UX Designer',
    description: 'Portfolio-friendly layout for UX and product design roles.',
    category: 'creative',
    categoryLabel: 'Creative',
    isPremium: true,
    colors: 'from-pink-500 to-purple-700',
  },
  {
    id: 'boardroom-template',
    name: 'Boardroom Elite',
    description: 'High-end executive format with leadership-first storytelling.',
    category: 'executive',
    categoryLabel: 'Executive',
    isPremium: true,
    colors: 'from-amber-700 to-slate-900',
  },
  {
    id: 'impact-template',
    name: 'Impact Ledger',
    description: 'Professional, metrics-focused resume optimized for ATS readability.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: false,
    isPopular: true,
    colors: 'from-blue-600 to-slate-900',
  },
  {
    id: 'noir-elegance',
    name: 'Noir Elegance',
    description: 'Dark luxury aesthetic with gold accents and serif typography for senior executives.',
    category: 'executive',
    categoryLabel: 'Executive',
    isPremium: true,
    colors: 'from-zinc-900 to-amber-700',
  },
  {
    id: 'swiss-precision',
    name: 'Swiss Precision',
    description: 'International typographic style with bold accents and grid-based layout.',
    category: 'creative',
    categoryLabel: 'Creative',
    isPremium: true,
    colors: 'from-rose-600 to-red-800',
  },
  {
    id: 'architect-blueprint',
    name: 'Architect Blueprint',
    description: 'Structured sidebar layout with warm tones inspired by architectural drawings.',
    category: 'professional',
    categoryLabel: 'Professional',
    isPremium: true,
    colors: 'from-slate-700 to-orange-700',
  },
  {
    id: 'vogue-editorial',
    name: 'Vogue Editorial',
    description: 'High-fashion editorial aesthetic with elegant typography.',
    category: 'creative',
    categoryLabel: 'Creative',
    isPremium: true,
    colors: 'from-stone-500 to-amber-700',
  },
  {
    id: 'carbon-terminal',
    name: 'Carbon Terminal',
    description: 'Terminal-style UI with syntax-inspired presentation for tech profiles.',
    category: 'tech',
    categoryLabel: 'Tech',
    isPremium: true,
    colors: 'from-indigo-700 to-slate-900',
  },
];

export const DEFAULT_TEMPLATE_ID = 'modern-professional';

export const TEMPLATE_ID_SET = new Set(TEMPLATE_CATALOG.map((t) => t.id));

export function isTemplateId(value: string): boolean {
  return TEMPLATE_ID_SET.has(value);
}

export function getTemplateById(value: string) {
  return TEMPLATE_CATALOG.find((t) => t.id === value);
}
